# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.provision "shell", inline: <<-SHELL
    yum check-update
    curl -fsSL https://get.docker.com/ | sh
    systemctl start docker
    systemctl enable docker
    usermod -aG docker vagrant
    echo "cd /vagrant" >> ~/.bashrc
  SHELL
  config.ssh.forward_agent = true
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 4
  end

end
