FROM centos:centos7

RUN yum -y update

RUN curl -sL https://rpm.nodesource.com/setup_8.x | bash -
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash

RUN sudo yum install -y nodejs

RUN echo 'alias ll="ls -al"' >> ~/.bashrc

EXPOSE 8080 8081 8082 9229 80
