FROM node:8

RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash

RUN apt-get update
RUN apt-get install -y vim

RUN echo 'alias ll="ls -al"' >> ~/.bashrc

EXPOSE 8080 8081 8082 9229 80
